import {
  Announcement,
  CompetitionGroup,
  CompetitionStage,
  Match,
  MatchResult,
  Profile,
  Sport,
  SportSlug,
  Team,
  Tournament
} from "@/lib/types";

export const tournamentSeed: Tournament = {
  id: "iasl-2026",
  name: "Inter Association Sports League",
  startDate: "2026-04-02",
  endDate: "2026-04-05",
  venue: "Central College Grounds"
};

export const sportsSeed: Sport[] = [
  {
    id: "cricket",
    name: "Cricket",
    color: "#f59e0b",
    rulesSummary: "T20 pool play narrows into knockout nights with a third-place board and seeded crossovers.",
    format: "8 teams, 2 groups, knockout plus bronze"
  },
  {
    id: "football",
    name: "Football",
    color: "#22c55e",
    rulesSummary: "Campus cup knockout with a third-place playoff and explicit penalty/late-change result handling.",
    format: "8 teams, knockout plus bronze"
  },
  {
    id: "volleyball",
    name: "Volleyball",
    color: "#38bdf8",
    rulesSummary: "Indoor bracket with byes, compact quarter-finals, and a live finals path.",
    format: "7 teams, bye-aware knockout plus bronze"
  },
  {
    id: "athletics",
    name: "Athletics",
    color: "#fb7185",
    rulesSummary: "Association result cards for heats and medal rounds, kept separate from bracket generation.",
    format: "Track heats plus medal rounds"
  }
];

export const teamsSeed: Team[] = [
  { id: "andhra-samithi", name: "Andhra Samithi", association: "A Block", sportIds: ["cricket", "football", "volleyball"], seed: 1, isActive: true },
  { id: "capitol", name: "Capitol", association: "B Block", sportIds: ["cricket", "football"], seed: 2, isActive: true },
  { id: "gurjari", name: "Gurjari", association: "C Block", sportIds: ["cricket", "volleyball", "athletics"], seed: 3, isActive: true },
  { id: "haryana-cultural", name: "Haryana Cultural Association", association: "D Block", sportIds: ["cricket", "athletics"], seed: 4, isActive: true },
  { id: "punjab-cultural", name: "Punjab Cultural Association", association: "E Block", sportIds: ["cricket", "football", "athletics"], seed: 5, isActive: true },
  { id: "udgam", name: "Udgam", association: "F Block", sportIds: ["cricket", "volleyball"], seed: 6, isActive: true },
  { id: "sangam", name: "Sangam", association: "G Block", sportIds: ["football", "volleyball", "athletics"], seed: 7, isActive: true },
  { id: "kairali", name: "Kairali", association: "H Block", sportIds: ["cricket", "athletics"], seed: 8, isActive: true },
  { id: "kannada-vedike", name: "Kannada Vedike", association: "I Block", sportIds: ["football", "volleyball"], seed: 9, isActive: true },
  { id: "pilani-tamil-mandram", name: "Pilani Tamil Mandram", association: "J Block", sportIds: ["football", "volleyball", "athletics"], seed: 10, isActive: true },
  { id: "madhyansh", name: "Madhyansh", association: "K Block", sportIds: ["cricket", "athletics"], seed: 11, isActive: true },
  { id: "maurya-vihar", name: "Maurya Vihar", association: "L Block", sportIds: ["cricket", "football"], seed: 12, isActive: true },
  { id: "marudhara", name: "Marudhara", association: "M Block", sportIds: ["cricket", "volleyball"], seed: 13, isActive: true },
  { id: "moruchhaya", name: "Moruchhaya", association: "N Block", sportIds: ["cricket", "athletics"], seed: 14, isActive: true },
  { id: "maharashtra-mandal", name: "Maharashtra Mandal", association: "O Block", sportIds: ["football", "volleyball"], seed: 15, isActive: true },
  { id: "utkal-samaj", name: "Utkal Samaj", association: "P Block", sportIds: ["cricket", "athletics"], seed: 16, isActive: true }
];

export const profilesSeed: Profile[] = [
  {
    id: "00000000-0000-0000-0000-000000000001",
    name: "Tournament Lead",
    email: "lead@college.edu",
    role: "super_admin",
    sportIds: ["cricket", "football", "volleyball", "athletics"]
  },
  {
    id: "00000000-0000-0000-0000-000000000002",
    name: "Cricket Admin",
    email: "cricket@college.edu",
    role: "sport_admin",
    sportIds: ["cricket"]
  }
];

export const competitionStagesSeed: CompetitionStage[] = [
  { id: "cricket-group-stage", sportId: "cricket", type: "group", label: "Pool Stage", orderIndex: 1, advancesCount: 2, isActive: true },
  { id: "cricket-knockout-stage", sportId: "cricket", type: "knockout", label: "Championship Bracket", orderIndex: 2, advancesCount: 1, isActive: true },
  { id: "cricket-placement-stage", sportId: "cricket", type: "placement", label: "Bronze Match", orderIndex: 3, advancesCount: 0, isActive: true },
  { id: "football-knockout-stage", sportId: "football", type: "knockout", label: "Cup Bracket", orderIndex: 1, advancesCount: 1, isActive: true },
  { id: "football-placement-stage", sportId: "football", type: "placement", label: "Third Place", orderIndex: 2, advancesCount: 0, isActive: true },
  { id: "volleyball-knockout-stage", sportId: "volleyball", type: "knockout", label: "Championship Ladder", orderIndex: 1, advancesCount: 1, isActive: true },
  { id: "volleyball-placement-stage", sportId: "volleyball", type: "placement", label: "Bronze Match", orderIndex: 2, advancesCount: 0, isActive: true },
  { id: "athletics-results-stage", sportId: "athletics", type: "group", label: "Results Cards", orderIndex: 1, advancesCount: 0, isActive: true }
];

export const competitionGroupsSeed: CompetitionGroup[] = [
  { id: "cricket-group-a", stageId: "cricket-group-stage", sportId: "cricket", code: "Group A", orderIndex: 1 },
  { id: "cricket-group-b", stageId: "cricket-group-stage", sportId: "cricket", code: "Group B", orderIndex: 2 }
];

export const matchesSeed: Match[] = [
  {
    id: "cricket-ga-1",
    sportId: "cricket",
    round: "Group A Match 1",
    day: "2026-04-02",
    startTime: "10:00",
    venue: "Main Ground",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-a",
    roundIndex: 1,
    matchNumber: 1,
    teamAId: "andhra-samithi",
    teamBId: "capitol",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-ga-2",
    sportId: "cricket",
    round: "Group A Match 2",
    day: "2026-04-02",
    startTime: "13:00",
    venue: "Main Ground",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-a",
    roundIndex: 1,
    matchNumber: 2,
    teamAId: "gurjari",
    teamBId: "haryana-cultural",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-ga-3",
    sportId: "cricket",
    round: "Group A Match 3",
    day: "2026-04-03",
    startTime: "09:30",
    venue: "Main Ground",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-a",
    roundIndex: 1,
    matchNumber: 3,
    teamAId: "andhra-samithi",
    teamBId: "gurjari",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-ga-4",
    sportId: "cricket",
    round: "Group A Match 4",
    day: "2026-04-03",
    startTime: "13:00",
    venue: "Main Ground",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-a",
    roundIndex: 1,
    matchNumber: 4,
    teamAId: "capitol",
    teamBId: "haryana-cultural",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-gb-1",
    sportId: "cricket",
    round: "Group B Match 1",
    day: "2026-04-02",
    startTime: "16:00",
    venue: "Practice Oval",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-b",
    roundIndex: 1,
    matchNumber: 1,
    teamAId: "punjab-cultural",
    teamBId: "udgam",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-gb-2",
    sportId: "cricket",
    round: "Group B Match 2",
    day: "2026-04-02",
    startTime: "19:00",
    venue: "Practice Oval",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-b",
    roundIndex: 1,
    matchNumber: 2,
    teamAId: "kairali",
    teamBId: "madhyansh",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-gb-3",
    sportId: "cricket",
    round: "Group B Match 3",
    day: "2026-04-03",
    startTime: "16:00",
    venue: "Practice Oval",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-b",
    roundIndex: 1,
    matchNumber: 3,
    teamAId: "punjab-cultural",
    teamBId: "kairali",
    status: "live",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-gb-4",
    sportId: "cricket",
    round: "Group B Match 4",
    day: "2026-04-03",
    startTime: "20:00",
    venue: "Practice Oval",
    stageId: "cricket-group-stage",
    groupId: "cricket-group-b",
    roundIndex: 1,
    matchNumber: 4,
    teamAId: "udgam",
    teamBId: "madhyansh",
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-sf-1",
    sportId: "cricket",
    round: "Semi Final 1",
    day: "2026-04-04",
    startTime: "18:00",
    venue: "Main Ground",
    stageId: "cricket-knockout-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 1,
    teamAId: "andhra-samithi",
    teamBId: "madhyansh",
    status: "scheduled",
    winnerToMatchId: "cricket-final",
    winnerToSlot: "team_a",
    loserToMatchId: "cricket-third",
    loserToSlot: "team_a",
    nextMatchId: "cricket-final",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "cricket-sf-2",
    sportId: "cricket",
    round: "Semi Final 2",
    day: "2026-04-04",
    startTime: "21:00",
    venue: "Main Ground",
    stageId: "cricket-knockout-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 2,
    teamAId: "gurjari",
    teamBId: "udgam",
    status: "scheduled",
    winnerToMatchId: "cricket-final",
    winnerToSlot: "team_b",
    loserToMatchId: "cricket-third",
    loserToSlot: "team_b",
    nextMatchId: "cricket-final",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "cricket-third",
    sportId: "cricket",
    round: "Third Place",
    day: "2026-04-05",
    startTime: "16:00",
    venue: "Main Ground",
    stageId: "cricket-placement-stage",
    groupId: null,
    roundIndex: 3,
    matchNumber: 1,
    teamAId: null,
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "cricket-final",
    sportId: "cricket",
    round: "Grand Final",
    day: "2026-04-05",
    startTime: "20:00",
    venue: "Main Ground",
    stageId: "cricket-knockout-stage",
    groupId: null,
    roundIndex: 3,
    matchNumber: 1,
    teamAId: null,
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "football-qf-1",
    sportId: "football",
    round: "Quarter Final 1",
    day: "2026-04-03",
    startTime: "15:00",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 1,
    teamAId: "punjab-cultural",
    teamBId: "kannada-vedike",
    status: "completed",
    winnerToMatchId: "football-sf-1",
    winnerToSlot: "team_a",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "football-sf-1",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "football-qf-2",
    sportId: "football",
    round: "Quarter Final 2",
    day: "2026-04-03",
    startTime: "16:15",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 2,
    teamAId: "pilani-tamil-mandram",
    teamBId: "maharashtra-mandal",
    status: "live",
    winnerToMatchId: "football-sf-1",
    winnerToSlot: "team_b",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "football-sf-1",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "football-qf-3",
    sportId: "football",
    round: "Quarter Final 3",
    day: "2026-04-03",
    startTime: "17:30",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 3,
    teamAId: "andhra-samithi",
    teamBId: "capitol",
    status: "completed",
    winnerToMatchId: "football-sf-2",
    winnerToSlot: "team_a",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "football-sf-2",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "football-qf-4",
    sportId: "football",
    round: "Quarter Final 4",
    day: "2026-04-03",
    startTime: "18:45",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 4,
    teamAId: "maurya-vihar",
    teamBId: "sangam",
    status: "scheduled",
    winnerToMatchId: "football-sf-2",
    winnerToSlot: "team_b",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "football-sf-2",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "football-sf-1",
    sportId: "football",
    round: "Semi Final 1",
    day: "2026-04-04",
    startTime: "16:00",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 1,
    teamAId: "kannada-vedike",
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: "football-final",
    winnerToSlot: "team_a",
    loserToMatchId: "football-third",
    loserToSlot: "team_a",
    nextMatchId: "football-final",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "football-sf-2",
    sportId: "football",
    round: "Semi Final 2",
    day: "2026-04-04",
    startTime: "18:00",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 2,
    teamAId: "andhra-samithi",
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: "football-final",
    winnerToSlot: "team_b",
    loserToMatchId: "football-third",
    loserToSlot: "team_b",
    nextMatchId: "football-final",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "football-third",
    sportId: "football",
    round: "Third Place",
    day: "2026-04-05",
    startTime: "15:30",
    venue: "Football Turf",
    stageId: "football-placement-stage",
    groupId: null,
    roundIndex: 3,
    matchNumber: 1,
    teamAId: null,
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "football-final",
    sportId: "football",
    round: "Grand Final",
    day: "2026-04-05",
    startTime: "18:30",
    venue: "Football Turf",
    stageId: "football-knockout-stage",
    groupId: null,
    roundIndex: 3,
    matchNumber: 1,
    teamAId: null,
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "volleyball-qf-1",
    sportId: "volleyball",
    round: "Quarter Final 1",
    day: "2026-04-03",
    startTime: "11:00",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 1,
    teamAId: "sangam",
    teamBId: null,
    status: "completed",
    winnerToMatchId: "volleyball-sf-1",
    winnerToSlot: "team_a",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "volleyball-sf-1",
    nextSlot: "team_a",
    isBye: true
  },
  {
    id: "volleyball-qf-2",
    sportId: "volleyball",
    round: "Quarter Final 2",
    day: "2026-04-03",
    startTime: "12:30",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 2,
    teamAId: "udgam",
    teamBId: "gurjari",
    status: "completed",
    winnerToMatchId: "volleyball-sf-1",
    winnerToSlot: "team_b",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "volleyball-sf-1",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "volleyball-qf-3",
    sportId: "volleyball",
    round: "Quarter Final 3",
    day: "2026-04-03",
    startTime: "14:00",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 3,
    teamAId: "marudhara",
    teamBId: "andhra-samithi",
    status: "scheduled",
    winnerToMatchId: "volleyball-sf-2",
    winnerToSlot: "team_a",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "volleyball-sf-2",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "volleyball-qf-4",
    sportId: "volleyball",
    round: "Quarter Final 4",
    day: "2026-04-03",
    startTime: "15:30",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 4,
    teamAId: "kannada-vedike",
    teamBId: "maharashtra-mandal",
    status: "postponed",
    winnerToMatchId: "volleyball-sf-2",
    winnerToSlot: "team_b",
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "volleyball-sf-2",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "volleyball-sf-1",
    sportId: "volleyball",
    round: "Semi Final 1",
    day: "2026-04-04",
    startTime: "16:30",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 1,
    teamAId: "sangam",
    teamBId: "udgam",
    status: "completed",
    winnerToMatchId: "volleyball-final",
    winnerToSlot: "team_a",
    loserToMatchId: "volleyball-third",
    loserToSlot: "team_a",
    nextMatchId: "volleyball-final",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "volleyball-sf-2",
    sportId: "volleyball",
    round: "Semi Final 2",
    day: "2026-04-04",
    startTime: "18:00",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 2,
    teamAId: null,
    teamBId: null,
    status: "postponed",
    winnerToMatchId: "volleyball-final",
    winnerToSlot: "team_b",
    loserToMatchId: "volleyball-third",
    loserToSlot: "team_b",
    nextMatchId: "volleyball-final",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "volleyball-third",
    sportId: "volleyball",
    round: "Third Place",
    day: "2026-04-05",
    startTime: "14:30",
    venue: "Indoor Arena",
    stageId: "volleyball-placement-stage",
    groupId: null,
    roundIndex: 3,
    matchNumber: 1,
    teamAId: "udgam",
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "volleyball-final",
    sportId: "volleyball",
    round: "Grand Final",
    day: "2026-04-05",
    startTime: "17:00",
    venue: "Indoor Arena",
    stageId: "volleyball-knockout-stage",
    groupId: null,
    roundIndex: 3,
    matchNumber: 1,
    teamAId: "sangam",
    teamBId: null,
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  },
  {
    id: "athletics-heat-1",
    sportId: "athletics",
    round: "100m Heat 1",
    day: "2026-04-03",
    startTime: "16:15",
    venue: "Track Oval",
    stageId: "athletics-results-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 1,
    teamAId: "punjab-cultural",
    teamBId: "pilani-tamil-mandram",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "athletics-final",
    nextSlot: "team_a",
    isBye: false
  },
  {
    id: "athletics-heat-2",
    sportId: "athletics",
    round: "100m Heat 2",
    day: "2026-04-03",
    startTime: "16:30",
    venue: "Track Oval",
    stageId: "athletics-results-stage",
    groupId: null,
    roundIndex: 1,
    matchNumber: 2,
    teamAId: "gurjari",
    teamBId: "utkal-samaj",
    status: "completed",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: "athletics-final",
    nextSlot: "team_b",
    isBye: false
  },
  {
    id: "athletics-final",
    sportId: "athletics",
    round: "100m Final",
    day: "2026-04-05",
    startTime: "16:45",
    venue: "Track Oval",
    stageId: "athletics-results-stage",
    groupId: null,
    roundIndex: 2,
    matchNumber: 1,
    teamAId: "pilani-tamil-mandram",
    teamBId: "utkal-samaj",
    status: "scheduled",
    winnerToMatchId: null,
    winnerToSlot: null,
    loserToMatchId: null,
    loserToSlot: null,
    nextMatchId: null,
    nextSlot: null,
    isBye: false
  }
];

export const resultsSeed: MatchResult[] = [
  {
    matchId: "cricket-ga-1",
    winnerTeamId: "andhra-samithi",
    teamAScore: 148,
    teamBScore: 142,
    decisionType: "normal",
    scoreSummary: "148/4 vs 142/7",
    note: "Andhra defended tightly at the death.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-02T12:10:00+05:30"
  },
  {
    matchId: "cricket-ga-2",
    winnerTeamId: "gurjari",
    teamAScore: 151,
    teamBScore: 144,
    decisionType: "normal",
    scoreSummary: "151/5 vs 144/8",
    note: "Gurjari closed on top after a late batting burst.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-02T15:35:00+05:30"
  },
  {
    matchId: "cricket-ga-3",
    winnerTeamId: "andhra-samithi",
    teamAScore: 133,
    teamBScore: 129,
    decisionType: "normal",
    scoreSummary: "133/7 vs 129/9",
    note: "A low-scoring win keeps Andhra top of Group A.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T11:45:00+05:30"
  },
  {
    matchId: "cricket-ga-4",
    winnerTeamId: "capitol",
    teamAScore: 155,
    teamBScore: 153,
    decisionType: "normal",
    scoreSummary: "155/6 vs 153/7",
    note: "Capitol stayed alive with a chase in the final over.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T15:10:00+05:30"
  },
  {
    matchId: "cricket-gb-1",
    winnerTeamId: "udgam",
    teamAScore: 139,
    teamBScore: 141,
    decisionType: "normal",
    scoreSummary: "139/8 vs 141/4",
    note: "Udgam paced the chase expertly.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-02T17:40:00+05:30"
  },
  {
    matchId: "cricket-gb-2",
    winnerTeamId: "madhyansh",
    teamAScore: 121,
    teamBScore: 126,
    decisionType: "normal",
    scoreSummary: "121/9 vs 126/5",
    note: "Madhyansh earned the cleaner net run-rate start.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-02T20:50:00+05:30"
  },
  {
    matchId: "cricket-gb-3",
    winnerTeamId: null,
    teamAScore: 67,
    teamBScore: 66,
    decisionType: "normal",
    scoreSummary: "67/1 vs 66/3",
    note: "Powerplay underway with Punjab narrowly ahead.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T16:35:00+05:30"
  },
  {
    matchId: "football-qf-1",
    winnerTeamId: "kannada-vedike",
    teamAScore: 1,
    teamBScore: 1,
    decisionType: "penalties",
    scoreSummary: "1 - 1 (4-3 pens)",
    note: "Kannada Vedike survived a penalty shootout.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T15:55:00+05:30"
  },
  {
    matchId: "football-qf-2",
    winnerTeamId: null,
    teamAScore: 1,
    teamBScore: 1,
    decisionType: "normal",
    scoreSummary: "1 - 1",
    note: "Second half in progress.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T16:55:00+05:30"
  },
  {
    matchId: "football-qf-3",
    winnerTeamId: "andhra-samithi",
    teamAScore: 2,
    teamBScore: 0,
    decisionType: "normal",
    scoreSummary: "2 - 0",
    note: "A composed defensive display secured the shutout.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T18:15:00+05:30"
  },
  {
    matchId: "volleyball-qf-1",
    winnerTeamId: "sangam",
    teamAScore: 1,
    teamBScore: 0,
    decisionType: "walkover",
    scoreSummary: "Bye to semi-final",
    note: "Top seed Sangam advances on a bracket bye.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T11:05:00+05:30"
  },
  {
    matchId: "volleyball-qf-2",
    winnerTeamId: "udgam",
    teamAScore: 2,
    teamBScore: 1,
    decisionType: "normal",
    scoreSummary: "25-21, 18-25, 15-12",
    note: "Udgam held firm in the decider.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T13:25:00+05:30"
  },
  {
    matchId: "volleyball-sf-1",
    winnerTeamId: "sangam",
    teamAScore: 3,
    teamBScore: 1,
    decisionType: "normal",
    scoreSummary: "25-19, 22-25, 25-17, 25-20",
    note: "Sangam reaches the final with a balanced attack.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-04T17:40:00+05:30"
  },
  {
    matchId: "athletics-heat-1",
    winnerTeamId: "pilani-tamil-mandram",
    teamAScore: 12,
    teamBScore: 11,
    decisionType: "normal",
    scoreSummary: "11.8s vs 12.1s",
    note: "Pilani Tamil Mandram topped Heat 1.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T16:22:00+05:30"
  },
  {
    matchId: "athletics-heat-2",
    winnerTeamId: "utkal-samaj",
    teamAScore: 12,
    teamBScore: 11,
    decisionType: "normal",
    scoreSummary: "11.9s vs 12.0s",
    note: "Photo finish separated the field in Heat 2.",
    updatedBy: profilesSeed[0].id,
    updatedAt: "2026-04-03T16:35:00+05:30"
  }
];

export const announcementsSeed: Announcement[] = [
  {
    id: "announce-1",
    title: "Volunteer briefing moved to 3:15 PM",
    body: "All venue volunteers should report at the media desk 15 minutes earlier than planned for access badge pickup.",
    visibility: "public",
    pinned: true,
    publishedAt: "2026-04-02T09:00:00+05:30",
    isPublished: true
  },
  {
    id: "announce-2",
    title: "Football quarter-final now in extra time",
    body: "The second football quarter-final remains level and may move to penalties. Crowd access remains restricted near the benches.",
    visibility: "public",
    pinned: false,
    publishedAt: "2026-04-03T16:50:00+05:30",
    isPublished: true
  },
  {
    id: "announce-3",
    title: "Volleyball semi-final lane updated",
    body: "One indoor court match has been postponed after a power reset. Builder mode shows the integrity warning until the slot is rescheduled.",
    visibility: "admin",
    pinned: false,
    publishedAt: "2026-04-03T17:10:00+05:30",
    isPublished: true
  }
];

export const sportOrder: SportSlug[] = ["cricket", "football", "volleyball", "athletics"];
